openapi: 3.0.4
info:
  title: Random Joke
  description: >-
    Random Joke is a simple tool for getting random jokes. It returns a random
    joke from a collection of jokes.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/randomjoke:
    get:
      summary: Get Random Joke
      description: Get a random joke from a collection of jokes
      operationId: randomjoke
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  score: 7
                  setup: >-
                    Why is the space between a woman's chest and her hips called
                    a waist?
                  punchline: Because you could easily fit another pair of tits in there.
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
